name: Test Java Application

on:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    # Checkout repository
    - name: Checkout code
      uses: actions/checkout@v3

    # Set up Java environment
    - name: Set up JDK
      uses: actions/setup-java@v3
      with:
        java-version: '17'

    # Run tests
    - name: Run tests
      run: ./gradlew test